### ISSUE TITLE
Login broken :/

### ISSUE THREAD

**Issue by itsN1X** [VaTz88/VzBlog#1]
I Think I broke your login authenticator serving at heroku.
I tried to pull // fix it but it seems that your gh-repo source is NOT the same as the one deployed there at herokuapps..
Sorry,
Happy New Years' V
( X

**Comment by itsN1X** [comment]
I found a workaround, but its only a workaround. I think nobody else can login now, not even you.
Sorry, again : (

**Comment by vatz88** [comment]
Hey chill!

I think you changed the email. Not sure but will check it.

The app is not hack proof actually. There are loopholes I'm aware of but lazy to fix them >.<

**Comment by itsN1X** [comment]
came back on?

**Comment by itsN1X** [comment]
Yeah, fixed! What'd you do?
:100:

**Comment by vatz88** [comment]
I didn't do anything!
You should tell me what you did??

**Comment by vatz88** [comment]
Actually the heroku limit for free database also applies when new article is published but I have not hard-coded any checks in the backend for it.

**Comment by itsN1X** [comment]
nm, a 0D exp. It's back like normal before . nice project though!

**Comment by vatz88** [comment]
Thanks :)

**Comment by itsN1X** [comment]
Sorry for disturbing, HNY : )

**Comment by vatz88** [comment]
Never mind! Happy new year to you too
